---
# tasks file for nginx

- include_vars: "stage_{{ ansible_nodename.split('.')[1] }}.yml"

- name: Install nginx
  yum:
   name: nginx
   state: present

- name: ensure default conf is absent
  file:
   path: /etc/nginx/conf.d/default.conf
   state: absent

- name: Set up nginx_conf
  template:
   src: nginx.conf.j2
   dest: /etc/nginx/nginx.conf
   owner: root
   group: root
   mode: 0644
  notify: restart nginx

- name: Set up nginx_virtualhosts
  template:
   src: "{{ item }}.j2"
   dest: "/etc/nginx/conf.d/{{ item }}"
   owner: root
   group: root
   mode: 0644
  notify: restart nginx
  with_items:
   - lb.conf

- name: Service nginx
  service:
   name: nginx
   state: started
   enabled: true
